# Generated by Django 2.2 on 2022-04-18 18:14

from django.db import migrations, models
import django.db.models.deletion
import forms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sessionKey', models.CharField(editable=False, max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=100)),
                ('whoIsRespondent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sessionKey', models.CharField(editable=False, max_length=100)),
                ('usePOZ', models.BooleanField()),
                ('freqOfVisits', models.CharField(max_length=100)),
                ('isPunctual', models.BooleanField()),
                ('correctDateOfEConsultation', models.BooleanField()),
                ('isProblemResolved', models.BooleanField()),
                ('wasVisitProposed', models.BooleanField()),
                ('wereInstructionsClear', models.BooleanField()),
                ('purposeOfEConsultation', models.CharField(max_length=100)),
                ('useOfETechniques', models.BooleanField()),
                ('isPreparedBeforeEConsultation', models.BooleanField()),
                ('respondentID', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='forms.General')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sessionKey', models.CharField(editable=False, max_length=100)),
                ('numberOfEConsults', models.IntegerField()),
                ('numberOfVisits', models.IntegerField()),
                ('technicalSkillsRating', models.IntegerField()),
                ('howManyEConsultsNeedingVisits', models.IntegerField()),
                ('arePatientsPrepared', models.BooleanField()),
                ('howManyPatientsDontAnswer', models.IntegerField()),
                ('seriousnessOfPatients', models.CharField(max_length=100)),
                ('cancellingIfNoContact', models.BooleanField()),
                ('limitedTrust', models.BooleanField()),
                ('eTechniquesAndTimeEfficiency', models.BooleanField()),
                ('eTechniquesAndWorkEase', models.BooleanField()),
                ('fearOfReturning', models.CharField(max_length=100)),
                ('respondentID', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='forms.General')),
            ],
        ),
        migrations.CreateModel(
            name='AllGroups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sessionKey', models.CharField(editable=False, max_length=100)),
                ('didTechnicalProblemsOccur', models.BooleanField()),
                ('eConsultationVsVisit', models.CharField(max_length=100)),
                ('eConsultationAsStandard', models.CharField(max_length=100)),
                ('accessibilityVsLimitingEConsults', models.CharField(max_length=100)),
                ('eConsultationVsChildren', models.CharField(max_length=100)),
                ('queuesAndVisits', models.CharField(max_length=100)),
                ('whoDecidesWhichForm', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('respondentID', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='forms.General')),
            ],
        ),
    ]
