# Generated by Django 2.2 on 2022-04-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=100)),
                ('whoIsRespondent', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
