# Generated by Django 4.0.4 on 2022-04-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20220419_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='lengthOfEConsults',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='lengthOfVisits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='yearsOfExperience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='general',
            name='education',
            field=models.CharField(default='University', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='general',
            name='employment',
            field=models.CharField(default='Student', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='fearOfViolatingConfidentiality',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='wasDoctorEngaged',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='whenWasEConsultation',
            field=models.CharField(default='SameDay', max_length=100),
            preserve_default=False,
        ),
    ]
