# Generated by Django 2.2 on 2022-04-14 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('didTechnicalProblemsOccur', models.BooleanField()),
                ('eConsultationVsVisit', models.CharField(max_length=100)),
                ('eConsultationAsStandard', models.CharField(max_length=100)),
                ('accessibilityVsLimitingEConsults', models.CharField(max_length=100)),
                ('eConsultationVsChildren', models.CharField(max_length=100)),
                ('queuesAndVisits', models.CharField(max_length=100)),
                ('whoDecidesWhichForm', models.CharField(max_length=100)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='isProblemResolved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='useOfEPrescription',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='useOfEReferral',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='useOfESickLeave',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='wasVisitProposed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='wereInstructionsClear',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfEConsults', models.IntegerField()),
                ('technicalSkillsRating', models.IntegerField()),
                ('avgTimeToFairEConsult', models.CharField(max_length=100)),
                ('howManyEConsultsNeedingVisits', models.IntegerField()),
                ('arePatientsPrepared', models.BooleanField()),
                ('howManyPatientsDontAnswer', models.IntegerField()),
                ('seriousnessOfPatients', models.CharField(max_length=100)),
                ('cancellingIfNoContact', models.BooleanField()),
                ('limitedTrust', models.BooleanField()),
                ('eTechniquesAndTimeEfficiency', models.BooleanField()),
                ('eTechniquesAndWorkEase', models.BooleanField()),
                ('fearOfReturning', models.BooleanField()),
                ('respondentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.General')),
            ],
        ),
    ]
