# Generated by Django 2.2 on 2022-04-15 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20220414_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='respondentId',
            new_name='respondentID',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='respondentId',
            new_name='respondentID',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='avgTimeToFairEConsult',
        ),
        migrations.AddField(
            model_name='doctor',
            name='allGroupsID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forms.AllGroups'),
        ),
        migrations.AddField(
            model_name='patient',
            name='allGroupsID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forms.AllGroups'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fearOfReturning',
            field=models.CharField(max_length=100),
        ),
    ]
