# Generated by Django 2.2 on 2022-04-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20220415_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='allGroupsID',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='allGroupsID',
        ),
        migrations.AddField(
            model_name='general',
            name='allGroupsID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forms.AllGroups'),
        ),
    ]
