# Generated by Django 2.2 on 2022-04-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20220415_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='allGroupsID',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='allGroupsID',
        ),
        migrations.AddField(
            model_name='allgroups',
            name='respondentID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forms.General'),
        ),
    ]
