# Generated by Django 2.2 on 2022-04-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20220415_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allgroups',
            name='respondentID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forms.General'),
        ),
    ]
