# Generated by Django 2.2 on 2022-04-15 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20220415_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='respondentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.General'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='respondentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.General'),
        ),
    ]
