# Generated by Django 2.2 on 2022-04-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_auto_20220415_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allgroups',
            name='respondentID',
        ),
    ]
