# Generated by Django 2.2 on 2022-04-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_remove_allgroups_respondentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='respondentID',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='respondentID',
        ),
    ]
