# Generated by Django 2.2 on 2022-04-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_auto_20220415_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='allgroups',
            name='respondentID',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='forms.General'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='respondentID',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='forms.General'),
        ),
        migrations.AddField(
            model_name='patient',
            name='preparationBeforeConsultation',
            field=models.CharField(choices=[('PESEL', 'PESEL do identyfikacji tożsamości,'), ('penAndPaper', 'kartkę i długopis,'), ('self-controlJournal', 'dzienniczek samokontroli,'), ('testResults', 'wyniki badań,'), ('listOfMedicine', 'listę leków,'), ('listOfQuestions', 'spis pytań do lekarza.')], default='', max_length=120),
        ),
        migrations.AddField(
            model_name='patient',
            name='respondentID',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='forms.General'),
        ),
    ]
