# Generated by Django 2.2 on 2022-04-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_auto_20220415_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='useOfEPrescription',
            new_name='isPreparedBeforeEConsultation',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='useOfEReferral',
            new_name='useOfETechniques',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='preparationBeforeConsultation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='useOfESickLeave',
        ),
    ]
