# Generated by Django 2.2 on 2022-04-17 15:52

from django.db import migrations, models
import django.db.models.deletion
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_auto_20220416_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='respondentID',
            field=models.OneToOneField(default=forms.models.default_general, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.General'),
        ),
        migrations.AddField(
            model_name='patient',
            name='purposeOfEConsultation',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allgroups',
            name='respondentID',
            field=models.OneToOneField(default=forms.models.default_general, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.General'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='respondentID',
            field=models.OneToOneField(default=forms.models.default_general, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.General'),
        ),
    ]
