# Generated by Django 2.2 on 2022-04-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_auto_20220417_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allgroups',
            name='respondentID',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='respondentID',
        ),
        migrations.AlterField(
            model_name='patient',
            name='respondentID',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.General'),
        ),
    ]
