# Generated by Django 2.2 on 2022-04-17 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_auto_20220417_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='allgroups',
            name='sessionKey',
            field=models.CharField(default=0, editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='sessionKey',
            field=models.CharField(default=0, editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='general',
            name='sessionKey',
            field=models.CharField(default=0, editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='sessionKey',
            field=models.CharField(default=0, editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allgroups',
            name='respondentID',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.General'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='respondentID',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.General'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='respondentID',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.General'),
        ),
    ]
