# Generated by Django 2.2 on 2022-04-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0026_auto_20220418_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='allgroups',
            name='sessionKey',
            field=models.CharField(default=1, editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='sessionKey',
            field=models.CharField(default=1, editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='sessionKey',
            field=models.CharField(default=1, editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
